name: Build and Test

on:
  pull_request:
    branches:
      - master
  check_run:
    types: [rerequested, requested_action]
  push:
    branches:
      - master
    tags:
      - 'v*'
  workflow_dispatch:

env:
  NODE_VERSION: '14'

defaults:
  run:
    shell: bash

jobs:

  buildReleaseVSIX:
    name: Build Release VSIX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: ${{env.NODE_VERSION}}

      - run: npm ci

      - run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: release-vsix
          path: '*.vsix'

  deployReleaseGitHub:
    name: Deploy Release to GitHub Release
    needs: [buildReleaseVSIX]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: release-channel
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-vsix
          path: .
      - name: Find filename
        shell: pwsh
        run: |
          $filename =  (Get-ChildItem *.vsix)[0].FullName
          echo "PACKAGE_FILENAME=$($filename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.PACKAGE_FILENAME}}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
